### ISSUE TITLE
[feature request] 词典

### ISSUE THREAD

**Issue by hulucc** [matrix1001/capslock-plus-plus#1]
目前有的功能是翻译，很多时候会希望看一下单词的含义，音标之类的

**Comment by matrix1001** [comment]
这个可以，我找个时间找找别人的api什么的，欢迎PR，需要修改的内容应该只有那一两个翻译函数。

**Comment by matrix1001** [comment]
![image](https://user-images.githubusercontent.com/32097922/48893638-c77c4b80-ee7b-11e8-81a2-3ac36cb0849f.png)

大概就是这样的了，我push了，但是还没正式加入功能。

**Comment by matrix1001** [comment]
我还没正式加进去你就close了😂
